@host=https://localhost:7037

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Luis",
    "lastName": "Romero",
    "email": "luis.romero@mail.com",
    "password": "Aa123456!"
}